language: python
python: 
  - "2.7"
services:
  - couchdb
before_script:
  - pip install coverage coveralls
script:
  - coverage run --source=cloudant-python setup.py test
after_success:
  - coveralls